name: Frontend CD

on:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  lint-and-build:
    name: CI dApp
    uses: ./.github/workflows/frontend-ci.yaml

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    environment: Prod
    concurrency: "${{ github.workflow }}-prod"
    needs:
      - lint-and-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"

      - name: Install algokit
        run: pipx install algokit

      - name: Install Vercel CLI
        working-directory: ./frontend
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: ./frontend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Create placeholder .env file
        uses: makerxstudio/shared-config/.github/actions/env-to-placeholders@main
        with:
          env-output-path: ./frontend/.env
          env-template-path: ./frontend/.env.template
          env-variable-prefix: VITE_

      - name: Build Project Artifacts
        working-directory: ./frontend
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Replace template vars
        uses: makerxstudio/shared-config/.github/actions/placeholder-transforms@main
        with:
          app-artifact-path: ./frontend/.vercel/output
          static-site-transforms: |-
            VITE_ALGOD_TOKEN:${{ secrets.VITE_ALGOD_TOKEN }}
            VITE_ALGOD_SERVER:${{ vars.VITE_ALGOD_SERVER }}
            VITE_ALGOD_PORT:${{ vars.VITE_ALGOD_PORT }}
            VITE_ALGOD_NETWORK:${{ vars.VITE_ALGOD_NETWORK }}
            VITE_INDEXER_SERVER:${{ vars.VITE_INDEXER_SERVER }}
            VITE_INDEXER_PORT:${{ vars.VITE_INDEXER_PORT }}
            VITE_INDEXER_TOKEN:${{ secrets.VITE_INDEXER_TOKEN }}
            VITE_ENVIRONMENT:${{ vars.VITE_ENVIRONMENT }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ./frontend
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        # Set your vercel project env variables on your site instance on https://vercel.com/dashboard
      
